In [165]:
import pandas as pd
import numpy as np

from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
#dms_data =pd.read_csv("data/DMS_Alhambra_Voltage_2018_2019.csv")
#ems_data=pd.read_csv("data/EMS_Alhambra_Voltage_2018_2019.csv")

In [127]:
dms_np = np.genfromtxt("data/DMS_Alhambra_Voltage_2018_2019.csv",delimiter=",")
ems_np = np.genfromtxt("data/EMS_Alhambra_Voltage_2018_2019.csv",delimiter=",")

In [128]:
ems_data = ems_np[1:,2:]
dms_data = dms_np[1:,2:]
ems_mean =np.mean(ems_data, axis=1)
dms_mean=np.mean(dms_data, axis=1)

In [129]:
#standardized data set: (x-mean)/std_dev

ems_standard = (ems_data - ems_mean.reshape(-1,1))/np.std(ems_data,axis=1).reshape(-1,1)


In [144]:
dms_standard = (dms_data - dms_mean.reshape(-1,1))/np.std(dms_data,axis=1).reshape(-1,1)

C:\Users\wangb2\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [154]:
dms_standard[dms_standard[:,]<0]

C:\Users\wangb2\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in less
  """Entry point for launching an IPython kernel.


array([-0.49623831, -0.1911905 , -0.43012176, ..., -0.17241395,
       -0.26850884, -0.33897925])

In [205]:
#normalize the data by maximum so it ranges from 0-1

ems_norm = ems_data/np.max(ems_data, axis=1).reshape(-1,1)
dms_norm = dms_data/np.max(dms_data,axis=1).reshape(-1,1)

In [206]:
ems_std = np.std(ems_norm, axis=1).reshape(-1,1)
dms_std = np.std(dms_norm,axis=1).reshape(-1,1)

In [207]:
print(np.mean(dms_std), np.max(dms_std), np.min(dms_std), "\n",dms_std, "\n")
print(np.mean(ems_std), np.max(ems_std), np.min(ems_std), "\n",ems_std, "\n")

0.028112459596653483 0.4139577763175094 0.0 
 [[0.00893754]
 [0.00836477]
 [0.00860158]
 [0.00984144]
 [0.00908308]
 [0.00369944]
 [0.00890319]
 [0.00995909]
 [0.01071504]
 [0.        ]
 [0.00943136]
 [0.00961503]
 [0.00924808]
 [0.00821495]
 [0.00292437]
 [0.00979529]
 [0.0067854 ]
 [0.        ]
 [0.01366862]
 [0.00930871]
 [0.2743747 ]
 [0.00882748]
 [0.00869744]
 [0.00952025]
 [0.04030602]
 [0.00864117]
 [0.0040543 ]
 [0.00378468]
 [0.02285673]
 [0.00966257]
 [0.01040542]
 [0.00928961]
 [0.00969029]
 [0.00350994]
 [0.00952091]
 [0.00976353]
 [0.00972998]
 [0.04005784]
 [0.04081396]
 [0.01026226]
 [0.00984486]
 [0.00909865]
 [0.01006642]
 [0.00812672]
 [0.00843356]
 [0.00677946]
 [0.00855106]
 [0.0495843 ]
 [0.41395778]
 [0.00295202]
 [0.27344724]
 [0.00894828]
 [0.01079114]
 [0.03526563]
 [0.00875247]
 [0.00883208]] 

0.05984342066475213 0.12401304319085116 0.006453644707016182 
 [[0.11780308]
 [0.11705999]
 [0.11911916]
 [0.12046961]
 [0.11718549]
 [0.11567561]
 [0.11568582]
 [0.11

In [109]:
#normalize the data by subtracting mean and dividing by std deviation.

array([1., 1., 1., ..., 1., 1., 1.])

In [161]:
ems_norm.shape

(34, 8760)

In [170]:
#################further process data into recordsx24x365 matrix to divide into roughly 2 week timeframes.
ems_recs = ems_norm.shape[0]
dms_recs = dms_norm.shape[0]

#ems_norm = ems_norm.reshape(ems_recs,8760)
#dms_norm = dms_norm.reshape(dms_recs,8760)

In [168]:
pca=PCA(n_components=24)

In [172]:
pca.fit(ems_norm)

PCA(copy=True, iterated_power='auto', n_components=24, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [175]:
#print(pca.explained_variance_ratio_)
print(pca.singular_values_)

[1.72075873e+02 7.78583615e+00 4.62150710e+00 3.66348774e+00
 2.22905017e+00 1.91376568e+00 1.44084677e+00 1.20643348e+00
 1.08778769e+00 9.85189033e-01 7.96335441e-01 5.93493065e-01
 5.48445639e-01 4.76934967e-01 4.40768934e-01 3.77221601e-01
 3.39195477e-01 2.92025298e-01 2.42026704e-01 2.11733776e-01
 1.57010869e-01 1.36168029e-01 6.00304665e-02 4.91890851e-02]


In [177]:
ems_pca = pca.transform(ems_norm)
ems_pca.shape

(34, 24)

In [186]:
kmeans=KMeans(n_clusters=12, random_state=10).fit(ems_pca)

In [189]:
kmeans.labels_.reshape(-1,1)

array([[ 3],
       [ 3],
       [ 3],
       [ 3],
       [ 1],
       [ 1],
       [ 1],
       [ 1],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 0],
       [ 9],
       [ 4],
       [ 6],
       [10],
       [11],
       [ 2],
       [ 8],
       [ 5],
       [ 7],
       [ 7],
       [ 7],
       [ 7],
       [ 7],
       [ 7],
       [ 7],
       [ 7],
       [ 7],
       [ 7],
       [ 7],
       [ 7]])

In [188]:
print(kmeans.score(ems_pca))

-4.65208703821736


In [193]:
dpca=PCA(n_components=24)
dpca.fit(dms_norm)
dms_pca = dpca.transform(dms_norm)

In [195]:
dkmeans=KMeans(n_clusters=12, random_state=10).fit(dms_pca)
print(dkmeans.labels_.reshape(-1,1))

[[ 5]
 [ 5]
 [ 5]
 [ 5]
 [ 5]
 [ 6]
 [ 5]
 [ 5]
 [ 5]
 [ 6]
 [ 5]
 [ 5]
 [ 5]
 [11]
 [ 6]
 [ 5]
 [ 5]
 [ 6]
 [ 5]
 [ 5]
 [ 3]
 [ 5]
 [ 5]
 [ 5]
 [ 0]
 [ 5]
 [ 6]
 [ 6]
 [10]
 [ 5]
 [ 7]
 [ 5]
 [ 5]
 [11]
 [ 5]
 [ 5]
 [ 5]
 [ 0]
 [ 1]
 [ 5]
 [ 5]
 [ 6]
 [ 5]
 [ 5]
 [ 5]
 [ 5]
 [ 5]
 [ 8]
 [ 2]
 [ 5]
 [ 4]
 [ 5]
 [ 5]
 [ 9]
 [ 5]
 [ 5]]
